### ISSUE TITLE
Improvement Checklist

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia-docs-deprecated#106]
- [ ]  Appearance
    - [ ]  `how to view locally` guide. Put [it](https://github.com/darwinia-network/docs/blob/master/content/en/wiki-contribute.md) to README.md
    - [x]  #108 Font optimization
    - [x]  Better and more unified screenshots
    - [x]  Better and more unified content layout
- [x]  Content correctness
    - [x]  Expired content, either delete or update
    - [x]  Check the screenshot content, 1. Chinese or English, 2. Network, 3. Address format, etc.
- [ ]  blog improvement
- [ ]  link `rfcs` to https://rfcs.darwinia.network

**Comment by acgxv** [comment]
https://github.com/darwinia-network/docs/blob/master/content/en/wiki-contribute.md
